apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blackbox-k8s
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: blackbox.k8s.com
    http:
      paths:
      - path: /
        backend:
          serviceName: blackbox
          servicePort: 9115
