kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: monitoring-ceph-fs
  namespace: monitoring
provisioner: ceph.com/cephfs
parameters:
  monitors: 192.168.208.27:6789,192.168.208.28:6789,192.168.208.29:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: monitoring
  claimRoot: /volumes/kubernetes/monitoring
